### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by KBPsystem777** [NovelCOVID/node-api#1]
Great API! 
Got this message while fetching data:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://corona.lmao.ninja/all. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
And It'll be more fun if CORS is enabled somehow :+1:

**Comment by meetmrkoushik** [comment]
How could we filter city wise ?

**Comment by KBPsystem777** [comment]
@meetmrkoushik Not possible for now on this API. Its up to country level only.

**Comment by EliteDaMyth** [comment]
@KBPsystem777 adding soon

**Comment by meetmrkoushik** [comment]
Do it as soon as possible. thanks
