### ISSUE TITLE
.countries(null, 'sort by'); Is not working

### ISSUE THREAD

**Issue by Joralmo** [NovelCOVID/node-api#20]
I have the following code

```
app.get('/countries', async (req, res) => {
	const { sort } = req.query;
	let countries;
	if (sort) {
		countries = await track.countries();
	} else {
		countries = await track.countries(null, sort);
	}
	res.send(countries);
});
```
But the answer is always the same, even if I send the sort parameter

![image](https://user-images.githubusercontent.com/19753876/78463671-3ccd7280-76a5-11ea-8363-d590051bfde6.png)

**Comment by Anish-Shobith** [comment]
the sort by sorts according to cases, todayCases , deaths, todayDeaths , etc ... not by by country names

**Comment by sayeduzzamancuet** [comment]
Why these methods are not working suddenly? It was working before

**Comment by Anish-Shobith** [comment]
Just got the issue , pushing changes soon!

**Comment by Anish-Shobith** [comment]
Fixed it! in the new release , reopen if the issue continues
