### ISSUE TITLE
Methods Not working

### ISSUE THREAD

**Issue by sayeduzzamancuet** [NovelCOVID/node-api#21]
Below the code I was using to consume this api. It is not workig now. What changed suddenly?

`const covid=require('novelcovid');
app.get('/api/states',(req,res)=>{
    (async () => {
        let states = await covid.getCountry();
        console.log(states);
        return res.json(states);
    })();
 });`

**Comment by Anish-Shobith** [comment]
@sayeduzzamancuet check the documentation again please , during the ts rewrite there was breaking change , now you need to invoke , getCountry are no longer methods now.

**Comment by sayeduzzamancuet** [comment]
`const  NovelCovid=require('novelcovid');

 app.get('/api/states',(req,res)=>{

        let obj = NovelCovid.all();
        console.log(obj);
        return res.json(obj);
 });`


still does not work. I am using this doc https://www.npmjs.com/package/novelcovid

**Comment by Anish-Shobith** [comment]
You need destruct the class and invoke the class , please the read the docs again.
Package exports NovelCovid
