### ISSUE TITLE
Inaccuracy for Ireland (Rep)

### ISSUE THREAD

**Issue by TheHappyShadies** [NovelCOVID/node-api#23]
On APR 10 the bot reported 1515 new cases for Ireland when the actual number is 480
Im pretty sure its just an unreliable source pulling the information and recommend pulling it from the official Irish GOV website 
https://www.gov.ie/en/news/7e0924-latest-updates-on-covid-19-coronavirus/

**Comment by Anish-Shobith** [comment]
This issue doesn't belong here , its just a wrapper for [NovelCovid API](https://github.com/NovelCOVID/API). It returns the value what the API returns.
