### ISSUE TITLE
Difference result for .countries() and .historical()

### ISSUE THREAD

**Issue by dediacc** [NovelCOVID/node-api#24]
The code 
```
import React, { Component } from 'react'
import { NovelCovid } from "novelcovid";

const covid = new NovelCovid();

export class Test extends Component {
 async componentDidMount(){
   const country = await covid.countries('usa')
   const history = await covid.historical(null, 'usa')
   console.log(country.deaths)
   const deaths = history.timeline.deaths
   console.log(deaths)
 } 
  render() {
    return (
      <div>

      </div>
    )
  }
}

export default Test
````
give two different result:
![usa](https://user-images.githubusercontent.com/30659198/79086639-f3e18200-7d66-11ea-9560-b7b2eb548c85.PNG)

I tried the same thing with 'russia', but it gives correct result
![russia](https://user-images.githubusercontent.com/30659198/79086636-f217be80-7d66-11ea-860f-d47c81fcc46a.PNG)

**Comment by Anish-Shobith** [comment]
They have added made few changes to the api. Yet to implement those but the above this is weird. using countries returns interface Country where deaths is a number ? but above it shows object ? are you sure the first image is correct ? and not of some other country ? I will update this tonight

**Comment by dediacc** [comment]
I am not sure what you mean. I am console logging 2 things, country.deaths and history.timeline.deaths. The most recent value (with key "4/12/20") of history.timeline.deaths is different than country.deaths. Shouldn't they be the same?

**Comment by dediacc** [comment]
my bad, didnt know it was actually from 2 different sources. I will close this.
