### ISSUE TITLE
Add name argument filter for .states() method

### ISSUE THREAD

**Issue by ngshiheng** [NovelCOVID/node-api#28]
The current API endpoint supports
`https://corona.lmao.ninja/states/New%20York`

However, for this package, it doesn't support filtering by a specific state

Suggestion:
- Make this work like `.countries('country name')`
```
.state('state name');   // For Specific State
```

**Comment by Anish-Shobith** [comment]
i am on it i should be pushing changes very soon

**Comment by Anish-Shobith** [comment]
Added!

**Comment by ngshiheng** [comment]
> Added!

Awesome, thanks! :smile:
