### ISSUE TITLE
NPM Package not working anymore?

### ISSUE THREAD

**Issue by SV932** [NovelCOVID/node-api#31]
It shows the below message 
"Deprecated, use /v2/countries"

**Comment by akanshgulati** [comment]
Getting same problem with yesterday methods coming in the API.

**Comment by akanshgulati** [comment]
@Anish-Shobith Could you check the PR #34 to solve this issue.

**Comment by josiahyeow** [comment]
If you're not using the yesterday methods which #34 mentions, I managed to resolve this issue by upgrading the novelcovid package to v1.2.4

**Comment by akanshgulati** [comment]
@josiahyeow I need yesterday data only. Well, we should make sure to migrate this package too with change in API's. Since, thousands of people are using this package daily, it really lowers down the trust if package unknowingly stop working even after migrating to new version. 

Also, as per semver versioning practises, this should be a 2.0.0 version all together if we are changing the methods here for fetching yesterday data.

**Comment by puf17640** [comment]
I am on it guys. I have a package which I keep up to date and I am currently talking to maintainers of this package to merge my code and let me maintain it.

**Comment by godwin-l** [comment]
> @josiahyeow I need yesterday data only. Well, we should make sure to migrate this package too with change in API's. Since, thousands of people are using this package daily, it really lowers down the trust if package unknowingly stop working even after migrating to new version.
> 
> Also, as per semver versioning practises, this should be a 2.0.0 version all together if we are changing the methods here for fetching yesterday data.
> 
> P.S. I understand you guys are doing a great job here but let's make this more reliable too.

true one

**Comment by puf17640** [comment]
@akanshgulati sorry to have to say but no its not a great job done here in my opinion, this is the official package for a (now) really big API, this has to be updated exactly when the API does to always have an up to date version reflecting exactly how the api has changed. i have done this with my own package "covidapi" but as it is not the official one, it wont get used that much. 

I am currently trying to push through (well actually im waiting for anish to answer my message so i can just push..) that my code gets merged over so I can also maintain it here and offer you guys an always up to date package.
