### ISSUE TITLE
yesterday data issue

### ISSUE THREAD

**Issue by killerbean26** [NovelCOVID/node-api#36]
will you update the api?
``async yesterday(country, sort) {
        if (country) {
            return node_fetch_1.default(`${this.baseURL}/v2/countries/${country}?yesterday=true`).then(json);
        }
        else if (!country && sort) {
            return node_fetch_1.default(`${this.baseURL}/v2/countries/${country}?yesterday=true${sort}`).then(json);
        }
        return node_fetch_1.default(`${this.baseURL}/v2/all?yesterday=true`).then(json);
    }``
I changed urls in index.js file which in node_modules/novelcovid and it worked. i just looked at the  [NovelCOVID github source](https://github.com/NovelCOVID/API/blob/master/tests/api_worldometers.spec.js).

**Comment by puf17640** [comment]
yes there will be an update asap! current maintainers cant right now, i am working on it

**Comment by godwin-l** [comment]
https://corona.lmao.ninja/v2/yesterday cannot get , that's was the issue I think...was that removed ? @puf17640

**Comment by puf17640** [comment]
well, the code that is in here right now is fixed yes, but the package on npm isnt yet, we will have to wait for either @Anish-Shobith or @apollyon600 to publish to npm

**Comment by Anish-Shobith** [comment]
I am on it currently , i fixed a lot of stuff and some breaking changes , got few more methods to work on and i will be pushing changes asap

**Comment by Anish-Shobith** [comment]
fixed it
