### ISSUE TITLE
Not getting data

### ISSUE THREAD

**Issue by sajjadgrw1** [NovelCOVID/node-api#38]
Not getting data for the last 2 days. 
This is message received in JSON response 
{"message":"This endpoint has been deprecated. Use /v2/all instead.","docs":"http://corona.lmao.ninja/docs"}
Is this repo still maintained ?

**Comment by godwin-l** [comment]
Yes @sajjadgrw1 , just upgrade to latest version 1.2.6 and also change the method names as per [this](https://www.npmjs.com/package/novelcovid)

`npm i novelcovid --save`
