### ISSUE TITLE
Error: invalid json response body at https://disease.sh/v2/historical/Brazil reason: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by LuXDAmore** [NovelCOVID/node-api#39]
Same error using the node-api [HERE](https://github.com/NovelCOVID/API/issues/575)

**Belgium is going well:**
_https://disease.sh/v2/historical/Belgium_
Response header: `content-type: application/json; charset=utf-8`

**Brazil is throwing this error:**
_https://disease.sh/v2/historical/Brazil_
Response header: `content-type: text/html; charset=utf-8`

> Error: invalid json response body at https://disease.sh/v2/historical/Brazil reason: Unexpected token < in JSON at position 0

**Comment by EliteDaMyth** [comment]
https://github.com/NovelCOVID/API/issues/575#issuecomment-617827167
