### ISSUE TITLE
0 instead of no value

### ISSUE THREAD

**Issue by kgoyal000** [NovelCOVID/node-api#43]
First thanks for this wonderful api , I am new and your api helps me to make a project and get jobs
My issue is
Where there are no cases instead of 0 api return nothing which breaks my google charts
Error: Row 6 has 1 columns, but must have 2 at Object.gvjs_ll [as arrayToDataTable] at drawRegionsMap function

Please make it 0 instead of no value

**Comment by puf17640** [comment]
This is how it initially was, but we got quite a few requests from developers to change it so they can see if a value was just not provided or it was actually 0. You should be able to use a function in your google charts to map null to 0.
