### ISSUE TITLE
https://github.com/NovelCOVID/node-api/issues/45

### ISSUE THREAD

**Issue by interpegasus** [NovelCOVID/node-api#46]
https://github.com/NovelCOVID/node-api/issues/45

**Comment by puf17640** [comment]
totally works for me tho...
it uses 1.0.3 (latest) version of @aero/centra

**Comment by interpegasus** [comment]
Thanks for the update @puf17640. 
It has been fixed by changing line 6 in CentraRequest.js in @aero/centra package.

**Before**
const {URL} = require('url');

**After**
const url = require('url');
